/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Euclidean_Distance_Transform_MT;

import org.junit.jupiter.api.Test;

class Euclidean_Distance_Transform_MTTest
{
    @Test
    void someLibraryMethodReturnsTrue()
    {
        Euclidean_Distance_Transform_MT classUnderTest = new Euclidean_Distance_Transform_MT();
        //assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
